apiVersion: v1
kind: ConfigMap
metadata:
  name: app-variables
  namespace: studyroom
  labels:
    app: studyroom
data:
  DB_NAME: "studyroom"
  DB_HOST: "postgres-service.studyroom.svc.cluster.local"
  DB_PORT: "5432"
  USE_S3: "TRUE"
