apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: chatroom
  name: chatroom
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatroom
  strategy: {}
  template:
    metadata:
      labels:
        app: chatroom
    spec:
      containers:
        - image: nginx
          name: nginx
