apiVersion: batch/v1
kind: Job
metadata:
  name: django-postgre-migrations
spec:
  template:
    spec:
      imagePullSecrets:
        - name: artifact-registry
      containers:
        

      restartPolicy: Never
