apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pv
  labels:
    app: studyroom
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-rwo
