apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox
  name: busybox
spec:
  containers:
    - args:
        - sleep
        - 1d
      image: busybox
      name: busybox
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgresdata
          subPath: data
  volumes:
    - name: postgresdata
      persistentVolumeClaim:
        claimName: postgres-pv
