apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: developement
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgres
      stage: developement
      type: db
  template:
    metadata:
      labels:
        app: postgres
        stage: developement
        type: db
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: user

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password

            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: app-variables
                  key: DB_NAME

          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
              subPath: data
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-pv

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: developement
spec:
  type: ClusterIP
  selector:
    app: postgres
    stage: developement
    type: db
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
