apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: studyroom
  labels:
    app: studyroom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      stage: development
      type: db
  template:
    metadata:
      labels:
        app: postgres
        stage: development
        type: db
    spec:
      containers:
        - name: postgres
          image: postgres
          resources:
            requests:
              memory: "50Mi"
              cpu: "30m"
            limits:
              memory: "50Mi"
              cpu: "30m"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_USER_PASSWORD

            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: app-variables
                  key: DB_NAME

          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
              subPath: data
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: db-pv

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: studyroom
spec:
  type: ClusterIP
  selector:
    app: postgres
    stage: development
    type: db
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
