apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv
  labels:
    name: postgres-pv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-rwo
